In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu126


In [3]:
## Creating tensors

scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
## Dimensions of a scalar

scalar.ndim

0

In [5]:
## Tensor back as python int

scalar.item()

7

In [6]:
# Vector

vector = torch.tensor([7, 7])

vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# Matrix

MATRIX = torch.tensor([[7, 8],
                      [9, 10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR

TENSOR = torch.tensor([[[1, 2, 3],
                       [3, 6, 9],
                       [2, 4, 5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

## Random tensors

In [16]:
# create a random tensor with pytorch of shape (3, 4)

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4122, 0.8028, 0.5319, 0.2992],
        [0.6904, 0.3475, 0.8640, 0.2651],
        [0.1865, 0.3855, 0.6655, 0.3456]])

In [17]:
random_tensor.ndim

2

In [18]:
# Create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(3, 224, 224)) # color channels, height, width

random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

## Creating tensors with 0 and 1 in pytorch

In [19]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

## Creating a range of tensors and tensors like 

In [23]:
# Create a range, use torch arange

zero_to_nine = torch.arange(0, 10)
zero_to_nine

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
# Creating tensors like

ten_zeros = torch.zeros_like(input=zero_to_nine)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

In [25]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None, # data type of the tensor
                               device=None, # what device is the tensor on
                              requires_grad=False) # whether to track gradient or not with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [26]:
float_32_tensor.dtype

torch.float32

In [27]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [28]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [29]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [30]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

## Getting information from tensors

In [31]:
#create a tensor

some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.9820, 0.0774, 0.1129, 0.5556],
        [0.5750, 0.3431, 0.5685, 0.5038],
        [0.1788, 0.4666, 0.5195, 0.2693]])

In [32]:
#find out details about the tensor

print(some_tensor)
print(f"Data type is : {some_tensor.dtype}")
print(f"Shape is : {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.9820, 0.0774, 0.1129, 0.5556],
        [0.5750, 0.3431, 0.5685, 0.5038],
        [0.1788, 0.4666, 0.5195, 0.2693]])
Data type is : torch.float32
Shape is : torch.Size([3, 4])
Device tensor is on: cpu


## Manipulating tensors(tensor operations)

In [33]:
# addition

tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [34]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [35]:
#multiply a tensor by 10

tensor*10

tensor([10, 20, 30])

In [36]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [37]:
tensor

tensor([1, 2, 3])

In [38]:
tensor-10

tensor([-9, -8, -7])

In [39]:
tensor/1

tensor([1., 2., 3.])

## Matrix multiplication

In [40]:
# element wise

tensor*tensor

tensor([1, 4, 9])

In [41]:
# matrix multiplication

torch.matmul(tensor, tensor)

tensor(14)

### One of the most common errors : shape errors

In [42]:
# Inner dimensions should match
# Resulting matrix have a shape of outer dimensions

torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.4654, 0.1947, 0.3621],
        [0.7183, 0.2638, 0.5249],
        [0.4484, 0.1941, 0.3549]])

In [43]:
tensor1 = torch.rand(3, 2)
tensor2 = torch.rand(3, 2)

In [44]:
#GIves error because of difference in shape
# torch.mm(tensor1, tensor2)

In [45]:
tensor1.shape, tensor2.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

### To fix the tensor shape issues, we transpose one of our tensors

In [46]:
tensor2

tensor([[0.8121, 0.6399],
        [0.8032, 0.3588],
        [0.4362, 0.7853]])

In [47]:
tensor2.T

tensor([[0.8121, 0.8032, 0.4362],
        [0.6399, 0.3588, 0.7853]])

## Finding min max sum etc (tensor aggregation)

In [48]:
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [49]:
# find min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [50]:
# find max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [51]:
# Find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [52]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Find the positional min max

In [53]:
x.argmin()

tensor(0)

In [54]:
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

In [55]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [56]:
y = torch.arange(1., 11.)
y, y.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [57]:
x_reshaped = x.reshape(1, 9)
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [58]:
x_reshaped = x.reshape(9, 1)
x_reshaped

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [59]:
y_reshaped = y.reshape(2, 5)
y_reshaped

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])

In [60]:
# view is similar to reshape but shares memory with the tensor it is created from
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [61]:
# changing z changes x

z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [62]:
# stack tensors on top of each other
# dim 0 is vertical stack
# dim 1 is horizontal stack

x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [66]:
x_reshaped, x_reshaped.shape

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [67]:
# squeeze - removes all the single dimensions from a target tensor

x_reshaped.squeeze(), x_reshaped.squeeze().shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [70]:
# Unsqueeze add a single dimension to a target tensor ar a specific dim(dimension)

x_squeezed = x_reshaped.squeeze()

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed.shape

torch.Size([1, 9])

In [71]:
x_squeezed.unsqueeze(dim=1)

tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [76]:
# torch permute rearranges the dimension of a target  tensor in a specified order
# Permute is a view so it shares the memory with the original tensor

x_original = torch.rand(size=(224, 224, 3))

# permute the original tensor to rarrange the axis (or dim) order

x_permuted = x_original.permute(2, 0, 1) # shifts axis 0 -> 1, 1 -> 2 and 2 -> 0
x_permuted.shape

torch.Size([3, 224, 224])

## Indexing (selecting data from tensors)

Indexing with PyTorch similar to indexing with NumPy

In [77]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [78]:
# lets index on our new tensor

x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [80]:
# lets index on middle bracket

x[0][0], x[0, 0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [83]:
# lets index on the most inner bracket

x[0][1][1]

tensor(5)

In [84]:
# you can use the ":" to select all of a target dimension

x[:, 0]

tensor([[1, 2, 3]])

In [87]:
# get all values of 0th and 1st dimension but index 1 of second dimension

x[:, :, 1]

tensor([[2, 5, 8]])

In [88]:
x[:, 1, 1]

tensor([5])

In [89]:
x[0][2][2]

tensor(9)

## PyTorch tensors & NumPy

We can interact with NumPy through pytorch to pass the data to and from NumPy.

In [94]:
# Numpy array to tensor
# going from numpy to pytorch default is float 64

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [95]:
# change the value of arra, will this do anything to tensor

array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [97]:
# Tensor to numpy

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [98]:
# change the tensot, what happens to numpy array

tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random, or controlling the randomness)

Every time setting random weights in neural networks can affect the training every time, to solve this we need same random numbers.

In [121]:
# gives different random numbers every time

torch.rand(3, 3), torch.rand(3, 3)

(tensor([[0.9516, 0.0753, 0.8860],
         [0.5832, 0.3376, 0.8090],
         [0.5779, 0.9040, 0.5547]]),
 tensor([[0.3423, 0.6343, 0.3644],
         [0.7104, 0.9464, 0.7890],
         [0.2814, 0.7886, 0.5895]]))

In [103]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

In [123]:
torch.rand(3, 4), torch.rand(3, 4)

(tensor([[0.9811, 0.0874, 0.0041, 0.1088],
         [0.1637, 0.7025, 0.6790, 0.9155],
         [0.2418, 0.1591, 0.7653, 0.2979]]),
 tensor([[0.8035, 0.3813, 0.7860, 0.1115],
         [0.2477, 0.6524, 0.6057, 0.3725],
         [0.7980, 0.8399, 0.1374, 0.2331]]))

In [129]:
torch.manual_seed(RANDOM_SEED)
torch.rand(3, 4), torch.rand(3, 4)

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8694, 0.5677, 0.7411, 0.4294],
         [0.8854, 0.5739, 0.2666, 0.6274],
         [0.2696, 0.4414, 0.2969, 0.8317]]))

In [134]:
torch.manual_seed(RANDOM_SEED)
print(torch.rand(3, 4))

torch.manual_seed(RANDOM_SEED)
print(torch.rand(3, 4))

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])


## Running PyTorch objects and tensors on GPU

In [135]:
torch.cuda.is_available()

True

In [136]:
# Setup device agnostic code

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [137]:
# Count the number of devices
torch.cuda.device_count()

1

## Putting tensors(and models) on GPU

GPU is fast.

In [138]:
tensor = torch.tensor([1, 2, 3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [140]:
# Move the tensor to GPU (if available)

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## Moving tensors back to CPU

In [141]:
# If tensor is on GPU, can't transform it to NumPy

# tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [142]:
# To fix the GPU tensor with NumPy issue we can first set it to cpu

tensor_back_on_cpu = tensor_on_gpu.cpu()
tensor_back_on_cpu

tensor([1, 2, 3])

In [143]:
tensor_back_on_cpu.numpy()

array([1, 2, 3], dtype=int64)